### ISSUE TITLE
Using old MySQL extension

### ISSUE THREAD

**Issue by smichaelsen** [Luzifer/PHPFramework#1]
Since PHP 5.0 it's recommended to use the MySQLi extension to work with a MySQL database.
Since PHP 5.5 the old MySQL extension is deprecated.

Please replace all mysql_\* calls with their corresponding functions from the MySQLi extension.

**Comment by Luzifer** [comment]
If you need this quickly you might want to open a pull request for it…

**Comment by smichaelsen** [comment]
In our fork we did the transition to mysqli, but i won't backport it because the frameworks have diverged too far.

https://github.com/app-zap/PHPFramework/blob/develop/classes/Persistence/MySQL.php

If you don't see the need for mysqli, you can close the issue. :white_check_mark:
