### ISSUE TITLE
Switch to MIT License

### ISSUE THREAD

**Issue by smichaelsen** [Luzifer/PHPFramework#7]
I want to suggest that you switch to the [MIT](http://choosealicense.com/licenses/mit/) license. It is quite similar to your License statement but as it is a standardized license it's easier to handle.

If not, I kindly ask you to grant us permission to publish our fork under the MIT license (including your name in the list of authors of course).

**Comment by Luzifer** [comment]
> The [Simplified BSD license](http://en.wikipedia.org/wiki/Simplified_BSD_license) used by FreeBSD is essentially identical to the MIT License, as it contains neither an advertising clause, nor a prohibition on promotional use of the copyright holder's name.
> -- http://en.wikipedia.org/wiki/MIT_License#Comparison_to_other_licenses
